apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-deployment
  labels:
    app: home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: home
  template:
    metadata:
      labels:
        app: home
    spec:
      containers:
      - name: home
        image: 913826031307.dkr.ecr.us-east-1.amazonaws.com/shopping-site-home:df10cce8cd5b1022f08ad3f6f2916e46916d4c0e
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: home-service
  labels:
    app: home
spec:
  type: ClusterIP
  selector:
    app: home
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
