apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-frontend-deployment
  namespace: microservices
  labels:
    app: main-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-frontend
  template:
    metadata:
      labels:
        app: main-frontend
    spec:
      containers:
        - name: main-frontend
          image: 913826031307.dkr.ecr.us-east-1.amazonaws.com/shopping-site-main:acf1f5d73d83f5f26543b38ec74b60f0e53a999a
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: main-service
  namespace: microservices
  labels:
    app: main-frontend
spec:
  type: ClusterIP
  selector:
    app: main-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80