apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlepay-deployment
  labels:
    app: googlepay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: googlepay
  template:
    metadata:
      labels:
        app: googlepay
    spec:
      containers:
      - name: googlepay
        image: 913826031307.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlepay:d2c3ff0e0ec533e2b44af07fdfe14ef2c7340d21
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: googlepay-service
  labels:
    app: googlepay
spec:
  type: ClusterIP
  selector:
    app: googlepay
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
