apiVersion: apps/v1
kind: Deployment
metadata:
  name: fashion-deployment
  labels:
    app: fashion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fashion
  template:
    metadata:
      labels:
        app: fashion
    spec:
      containers:
      - name: fashion
        image: 913826031307.dkr.ecr.us-east-1.amazonaws.com/shopping-site-fashion:9cad45c84148e3502f969a3729c29e845b58d9cc
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fashion-service
  labels:
    app: fashion
spec:
  type: ClusterIP
  selector:
    app: fashion
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
